# Generated by Django 5.2.4 on 2025-08-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_autor_nasc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='bio',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='nasc',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='nome',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='nacion',
            new_name='nacionality',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='sobrenome',
            new_name='name',
        ),
    ]
