# Generated by Django 5.2.4 on 2025-08-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_bio_autor_biography_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='biography',
            new_name='biografy',
        ),
    ]
