# Generated by Django 5.2.4 on 2025-08-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_biography_autor_biografy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('realese_date', models.DateField(blank=True, null=True)),
                ('autor', models.CharField(max_length=255)),
                ('pages', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
