# Generated by Django 5.2.4 on 2025-08-28 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editora', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='realese_date',
        ),
        migrations.AddField(
            model_name='book',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='dimensions',
            field=models.CharField(default=565),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='disponibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='Portugues'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='editora',
            field=models.ForeignKey(default=61, on_delete=django.db.models.deletion.CASCADE, to='api.publisher'),
            preserve_default=False,
        ),
    ]
